### PR TITLE
Distributed poller setup

### PR DESCRIPTION
**Pull request by RalfHerzog**
Here is the support for a distributed poller setup. Should fix most of #17. The `docker-compose-distributed-poller.yml` shows the variables to be set.

### CODE REVIEW

**Comment by RalfHerzog** [comment]
@setiseta how can we prevent starting memcached and rrdcached on all nodes? The `memcached.sh` and `rrdcached.sh` files are added to the docker image and started through the baseimage startup. Can we add the files under another directory and move them to `/etc/service/*/run` on container start?

**Comment by RalfHerzog** [comment]
Just as a note: I don't know why the WebUI does not offer to add a device to a specific poller group. The field is present but no poller groups are available. I tested the polling with an update on the database table `devices` => Field: `poller_group`

**Comment by setiseta** [comment]
@RalfHerzog I think with the startup files in a different directory and copy it to the right location based on environment variables should good.
But I havn't tested if it works with the baseimage.

**Comment by RalfHerzog** [comment]
Fortunately that does work :-)
Ready to merge or is something missing?

**Pull request merged**
